config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'users#match'

  resources :users do
    member do
      get 'profile'
      get 'register'
      get 'survey'
    end
    collection do
      get 'match'
      get 'result'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  def get_phenotypes
    unless phenotypes
      client = AwakensClient.new(self)
      json = client.get_phenotypes.to_json
      update!(phenotypes: json)
    end
    JSON.parse(phenotypes, object_class: OpenStruct)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def register

  end

  def profile
    @phenotypes = User.find(params[:id]).get_phenotypes
  end

  def survey
    @inherited_params_users = params["users"]
  end

  def match

  end

  def result
    users_ids = if params["users"]
                  params["users"].map(&:to_i)
                else
                  3.times.map do
                    rand(1..10)
                  end
                end
    @users = User.find(users_ids)
    user_phenotypes = @users.map { |user| user.get_phenotypes }
    @calc_result    = Calculator.instance.sum(user_phenotypes)
    @keywords        = Detector.instance.detect(@calc_result)
    @shops          = ShopClient.instance.search_keywords(@keywords.map { |elem| elem.keys }.flatten).take(5)
    @keys           = @shops.first.to_h.keys
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <!--<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false"
        aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>-->
      <a class="navbar-brand" href="/users/match"><%= image_tag("logo.png", {class: "img-rounded"})%></a>
      <a class="navbar-brand profile_btn" href="/users/1/profile">profile</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <!--<ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">Menu1</a></li>
        <li><a href="#contact">Menu2</a></li>
      </ul>-->
    </div>
    <!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Makakoi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--[if lt IE 9]>
    <script src="//cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="">
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/users/_user_icon.html.erb
<div class="matched_user">
  <%= image_tag(icon_path, {"class" => "icon active", "id" => 1})%>
  <p class="name active"><%= name %></p>
</div>

app/views/users/match.html.erb
<div class="container">
  <div class="wrap">
    <!--<h1>Searching....</h1>-->
    <!--<p class="lead"></p>-->
    <div id="ripple">
      <div class="circle"></div>
      <div class="circle"></div>
      <div class="circle"></div>
      <div class="circle"></div>
      <div class="circle"></div>
      <!--<div class="circle"></div>-->
      <div class="triangle"><%= image_tag("matching_center.png") %></div>
    </div>
    <div id="users">
      <div id="user1">
        <div class="icon_wrap"><%= image_tag("icon/kanao.png", {"class" => "icon non_active", "id" => 1})%></div>
        <p class="name">kanao</p>
      </div>
      <div id="user2">
        <div class="icon_wrap"><%= image_tag("icon/ikemura.png", {"class" => "icon non_active", "id" => 2})%></div>
        <p class="name">ikemura</p>
      </div>
      <div id="user3">
        <div class="icon_wrap"><%= image_tag("icon/komuro.png", {"class" => "icon non_active", "id" => 3})%></div>
        <p class="name">komuro</p>
      </div>
      <div id="user4">
        <div class="icon_wrap"><%= image_tag("icon/matsumoto.png", {"class" => "icon non_active", "id" => 4})%></div>
        <p class="name">matsumoto</p>
      </div>
      <div id="user5">
        <div class="icon_wrap"><%= image_tag("icon/matuda.png", {"class" => "icon non_active", "id" => 5})%></div>
        <p class="name">matsuda</p>
      </div>
    </div>
  </div>

  <div class="arrow">
    <%= image_tag("icon_triangle.png") %>
  </div>
  <div class="category">
    <div class="row">
      <div class="col-xs-12">
        <button class="btn" onclick="goToEnquete()">
          <span class="category_title"><<%= image_tag("pict/restraunt_title.png", {"class" => "category_title"})%></span><br>
          <img <%= image_tag("pict/restraunt.png", {"class" => "pict"})%>>
        </button>
        <button class="btn">
          <span class="category_title"><<%= image_tag("pict/healthcare_title.png", {"class" => "category_title"})%></span><br>
          <img <%= image_tag("pict/healthcare.png", {"class" => "pict"})%>>
        </button>
      </div>
      <div class="col-xs-12">
        <button class="btn">
          <span class="category_title"><<%= image_tag("pict/hobby_title.png", {"class" => "category_title"})%></span><br>
          <img <%= image_tag("pict/holiday.png", {"class" => "pict"})%>>
        </button>
        <button class="btn">
          <span class="category_title"><<%= image_tag("pict/hobby_title.png", {"class" => "category_title"})%></span><br>
          <img <%= image_tag("pict/hobby.png", {"class" => "pict"})%>>
        </button>
      </div>
    </div>
  </div>
</div>
<script>
  $(function() {

    $(".icon_wrap .icon").click(function(){
      if($(this).hasClass("non_active")){ // クリックされた要素がclickedクラスだったら
        $(this).removeClass("non_active");
        $(this).addClass("active");
      }else{
        $(this).removeClass("active");
        $(this).addClass("non_active");
      }
    });
  });
  function goToEnquete(){
    var arr = []
    $( ".icon.active" ).each(function() {
      arr.push("users%5B%5D=" + this.id)
    });
    var param = arr.join("&");
    // TODO: production書き換え
    var url = "http://makakoi.herokuapp.com/users/1/survey?" + param
    window.location.href = url
  }
</script>

app/views/users/profile.html.erb
<div class="container">
  <div class="wrap">
    <h3>Your Profile</h3>
    <%= render :partial => "user_icon", :locals => { :name => User.third.nick_name, :icon_path => User.third.icon_path } %>
    <table class="my_trend table table-striped table-hover ">
      <thead>
      <tr>
        <th>項目</th>
        <th>スコア</th>
        <th>詳細</th>
      </tr>
      </thead>
      <tbody>
        <% @phenotypes.each do |phenotype| %>
            <tr>
              <td><%= phenotype.table.phenotype.table.display_name %></td>
              <td><%= phenotype.table.summary.table.score %></td>
              <td><%= phenotype.table.summary.table.text %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/result.html.erb
<div class="container">
  <div class="result_wrap">
    <h3>YOUR MEMBER</h3>
    <div id="matched_group">
      <%- @users.each do |user| %>
          <%= render :partial => "user_icon", :locals => { :name => user.nick_name, :icon_path => user.icon_path } %>
      <%- end %>
    </div>
    <table class="table search_word">
      <tr><th>検索ワード</th><th>遺伝子</th></tr>
      <%- @keywords.each do |keyword| %>
        <tr><td><%= keyword.keys.first %></td><td><%= keyword[keyword.keys.first][0] %></td></tr>
      <%- end %>
    </table>
    <div id="store_list">
      <%- @shops.each_with_index do |shop, idx| %>
          <div class="flex-container">
            <div class="sotre flex-left">
              <p class="rank">RECOMMEND <%= idx %></p>
              <p class="store_name"><%= shop.name %></p>
              <p class="store_address"><%= shop.address %></p>
              <p class="money"><%= shop.budget.average %></p>
              <p class="tabelog_link"><%= link_to("食べログで見る", shop.urls.pc) %></p>
            </div>
            <div class="flex-right">
              <p class="food_img"><%= image_tag(shop.photo.pc.l) %></p>
            </div>
          </div>
      <%- end %>
    </div>
    <div style="height: 30px">もっと見る</div>
  </div>
</div>
</div>

app/views/users/survey.html.erb
<h1> TELL ME YOUR FEELING ?</H1>
<h6>(選択肢は未実装)</h6>
<table>
  <tr>
    <td align="left"> 1. 今日は胃が健康だ！</td>
    <td>
      <form>
        <div class="space">
          <%= image_tag("yes_hover_on.png", { style: "width: 20%; height: 20%" }) %>
          <%= image_tag("no_hover_off.png", { style: "width: 20%; height: 20%" }) %>
        </div>
      </form>
    </td>
  </tr>
  <tr>
    <td align="left">
      2. お酒を飲みたい気分
    </td>
    <td>
      <form>
        <div class="space">
          <%= image_tag("yes_hover_on.png", { style: "width: 20%; height: 20%" }) %>
          <%= image_tag("no_hover_off.png", { style: "width: 20%; height: 20%" }) %>
        </div>
      </form>
    </td>
  </tr>

  <tr>
    <td align="left">
      3. 安い場所がいい
    </td>
    <td>
      <form>
        <div class="space">
          <%= image_tag("yes_hover_off.png", { style: "width: 20%; height: 20%" }) %>
          <%= image_tag("no_hover_off.png", { style: "width: 20%; height: 20%" }) %>
        </div>
      </form>
    </td>
  </tr>

  <tr>
    <td align="left">
      4. 接待である
    </td>
    <td>
      <form>
        <div class="space">
          <%= image_tag("yes_hover_off.png", { style: "width: 20%; height: 20%" }) %>
          <%= image_tag("no_hover_off.png", { style: "width: 20%; height: 20%" }) %>
        </div>
      </form>
    </td>
  </tr>

  <tr>
    <td align="left">
      5. 友達同士で語り合いたい
    </td>
    <td>
      <form>
        <div class="space">
          <%= image_tag("yes_hover_off.png", { style: "width: 20%; height: 20%" }) %>
          <%= image_tag("no_hover_off.png", { style: "width: 20%; height: 20%" }) %>
        </div>
      </form>
    </td>
  </tr>
</table>
</div>
</div>

<div id="submit">
  <%= link_to("Submit", result_users_path(users: @inherited_params_users)) %>
</div>
<style>
  td {width: 50%;}
  table {margin-left: 16px;}
  #submit {margin-left: 16px; margin-top: 16px}
</style>